theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true

params:
  plausible: esee-degrowth2024.uvigo.gal
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-white.svg"
  i18n:
    positions:
      - primary
      - footer
  debug:
    productionUrl: "https://esee-degrowth2024.uvigo.gal"
  persons:
    single:
      backlinks: true